"""Add status to the status10

Revision ID: 554ad4858702
Revises: 06d2190cd80a
Create Date: 2025-04-08 09:47:17.273321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554ad4858702'
down_revision: Union[str, None] = '06d2190cd80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_post', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_post', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_post', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_post', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
