"""Updated logo4

Revision ID: b62f731e80ea
Revises: 52a497716ca4
Create Date: 2025-04-03 13:03:26.781453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62f731e80ea'
down_revision: Union[str, None] = '52a497716ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_form', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'application_form', 'user', ['user_id'], ['id'])
    op.drop_column('application_form', 'created_by')
    op.add_column('job_post', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'job_post', 'user', ['user_id'], ['id'])
    op.drop_column('job_post', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_post', type_='foreignkey')
    op.drop_column('job_post', 'user_id')
    op.add_column('application_form', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'application_form', type_='foreignkey')
    op.drop_column('application_form', 'user_id')
    # ### end Alembic commands ###
