"""Updated JobPost

Revision ID: a4f93e231c69
Revises: 0d9f2d4d3fa4
Create Date: 2025-04-02 14:26:57.572399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f93e231c69'
down_revision: Union[str, None] = '0d9f2d4d3fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_form', sa.Column('career_page_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'application_form', 'career_page', ['career_page_id'], ['id'])
    op.add_column('job_post', sa.Column('external_ids', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_post', 'external_ids')
    op.drop_constraint(None, 'application_form', type_='foreignkey')
    op.drop_column('application_form', 'career_page_id')
    # ### end Alembic commands ###
