"""Add status to the domain

Revision ID: 46ecc7c2ba0f
Revises: 3624e20d5da8
Create Date: 2025-04-07 19:00:02.309927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ecc7c2ba0f'
down_revision: Union[str, None] = '3624e20d5da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_page', sa.Column('domain', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_page', 'domain')
    # ### end Alembic commands ###
