"""create_career_page

Revision ID: e12f14659f89
Revises: 4afce9cdab86
Create Date: 2025-04-01 16:50:33.628724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12f14659f89'
down_revision: Union[str, None] = '4afce9cdab86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_page',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('favicon_url', sa.String(), nullable=True),
    sa.Column('social_media_url', sa.String(), nullable=True),
    sa.Column('langue_code', sa.String(), nullable=False),
    sa.Column('is_referral_program', sa.Boolean(), nullable=False),
    sa.Column('is_display_organization', sa.Boolean(), nullable=False),
    sa.Column('is_powered_by_manatal', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('contact_website', sa.String(), nullable=False),
    sa.Column('is_share_job_social_media', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_page')
    # ### end Alembic commands ###
