"""Updated CareerPageUser

Revision ID: ed45bf02ea64
Revises: bc11ba2f7149
Create Date: 2025-04-03 15:18:13.739264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed45bf02ea64'
down_revision: Union[str, None] = 'bc11ba2f7149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_page_user', 'status')
    op.drop_column('career_page_user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_page_user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('career_page_user', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
