"""Created ApplicationForm

Revision ID: 6171316e13d3
Revises: 687b1cb1f99e
Create Date: 2025-04-02 11:51:03.577246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6171316e13d3'
down_revision: Union[str, None] = '687b1cb1f99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_form',
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('job_post', sa.Column('application_form_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'job_post', 'application_form', ['application_form_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_post', type_='foreignkey')
    op.drop_column('job_post', 'application_form_id')
    op.drop_table('application_form')
    # ### end Alembic commands ###
