"""Changed user id

Revision ID: 68f12d8e137f
Revises: adcdff2f4caa
Create Date: 2025-04-09 10:34:48.277607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = '68f12d8e137f'
down_revision: Union[str, None] = 'adcdff2f4caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the column as nullable first
    op.add_column('career_page_user', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))

    # Fill it with a default value for existing rows (e.g., current time or a static timestamp)
    op.execute(
        f"UPDATE career_page_user SET last_active_at = '{datetime.now(timezone.utc).isoformat()}'"
    )

    # Then alter the column to be non-nullable
    op.alter_column('career_page_user', 'last_active_at', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_page_user', 'last_active_at')
    # ### end Alembic commands ###
