"""Updated logo3

Revision ID: 52a497716ca4
Revises: 45bad551daf8
Create Date: 2025-04-03 12:44:34.367840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52a497716ca4'
down_revision: Union[str, None] = '45bad551daf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_page', sa.Column('client_id', sa.String(), nullable=False))
    op.add_column('career_page', sa.Column('job_post_limit', sa.Integer(), nullable=False))
    op.drop_column('career_page', 'logo')
    op.drop_column('job_post', 'last_active_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post', sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('career_page', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('career_page', 'job_post_limit')
    op.drop_column('career_page', 'client_id')
    # ### end Alembic commands ###
