"""Add status to the status6

Revision ID: aa933945328c
Revises: a45d1cf6e28b
Create Date: 2025-04-07 20:10:25.891053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa933945328c'
down_revision: Union[str, None] = 'a45d1cf6e28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post', sa.Column('description', sa.String(), nullable=False))
    op.add_column('job_post', sa.Column('location', sa.String(), nullable=False))
    op.add_column('job_post', sa.Column('contract_details', sa.String(), nullable=False))
    op.add_column('job_post', sa.Column('external_ids', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_post', 'external_ids')
    op.drop_column('job_post', 'contract_details')
    op.drop_column('job_post', 'location')
    op.drop_column('job_post', 'description')
    # ### end Alembic commands ###
