"""Add status to the status5

Revision ID: aa1911ab2865
Revises: 9115307813b9
Create Date: 2025-04-07 19:52:06.206856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1911ab2865'
down_revision: Union[str, None] = '9115307813b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
job_post_work_type = sa.Enum('full_time', 'part_time', 'temporary', 'freelance', 'internship', 'apprenticeship', 'contractor', 'consultancy', name='job_post_work_type')

def upgrade() -> None:
    """Upgrade schema."""
    job_post_work_type.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_post', 'work_type',
               existing_type=sa.VARCHAR(),
               type_=job_post_work_type,
               existing_nullable=False,
               postgresql_using='work_type::job_post_work_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_post', 'work_type',
               existing_type=sa.Enum('full_time', 'part_time', 'temporary', 'freelance', 'internship', 'apprenticeship', 'contractor', 'consultancy', name='job_post_work_type'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
