"""Add status to the status7

Revision ID: cdf9e90ea951
Revises: aa933945328c
Create Date: 2025-04-07 20:12:52.422328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdf9e90ea951'
down_revision: Union[str, None] = 'aa933945328c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_post_link')
    op.drop_table('external_job_post')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_job_post',
    sa.Column('external_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='external_job_post_pkey'),
    sa.UniqueConstraint('external_id', name='external_job_post_external_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('job_post_link',
    sa.Column('job_post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('external_job_post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['external_job_post_id'], ['external_job_post.id'], name='job_post_link_external_job_post_id_fkey'),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_post.id'], name='job_post_link_job_post_id_fkey'),
    sa.PrimaryKeyConstraint('job_post_id', 'external_job_post_id', name='job_post_link_pkey')
    )
    # ### end Alembic commands ###
