"""Changed user id

Revision ID: d20b135d9028
Revises: 
Create Date: 2025-04-08 11:52:34.355259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20b135d9028'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant',
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('career_page',
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('job_post_limit', sa.Integer(), nullable=False),
    sa.Column('logo_key', sa.String(), nullable=True),
    sa.Column('favicon_key', sa.String(), nullable=True),
    sa.Column('social_media_key', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('is_referral_program', sa.Boolean(), nullable=False),
    sa.Column('is_display_organization', sa.Boolean(), nullable=False),
    sa.Column('is_powered_by_manatal', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'THB', 'AUD', 'BRL', 'ETB', 'HKD', 'IDR', 'INR', 'MYR', 'PHP', 'PKR', 'SGD', 'CNY', 'ZAR', 'AFN', 'ALL', 'AED', 'ARS', 'AMD', 'AZN', 'BIF', 'XOF', 'BDT', 'BGN', 'BHD', 'BAM', 'BZD', 'BOB', 'BND', 'NOK', 'BWP', 'XAF', 'CAD', 'CHF', 'CLP', 'CDF', 'NZD', 'COP', 'KMF', 'CVE', 'CRC', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'MAD', 'GBP', 'GEL', 'GHS', 'GNF', 'GTQ', 'HNL', 'HRK', 'HUF', 'IRR', 'IQD', 'ISK', 'ILS', 'JMD', 'JOD', 'JPY', 'KZT', 'KES', 'KHR', 'KRW', 'KWD', 'LBP', 'LYD', 'LKR', 'MOP', 'MDL', 'MGA', 'MXN', 'MKD', 'MMK', 'MZN', 'MUR', 'NAD', 'NGN', 'NIO', 'NPR', 'OMR', 'PAB', 'PEN', 'PLN', 'PYG', 'QAR', 'RON', 'RUB', 'RWF', 'SAR', 'SDG', 'SOS', 'RSD', 'SEK', 'SYP', 'TOP', 'TTD', 'TND', 'TRY', 'TWD', 'TZS', 'UGX', 'UAH', 'UYU', 'UZS', 'VEF', 'VND', 'YER', 'MNT', 'SRD', 'ZWL', 'ZMW', 'AOA', 'HTG', 'BBD', 'PGK', name='career_page_currency'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('contact_website', sa.String(), nullable=False),
    sa.Column('is_share_job_social_media', sa.Boolean(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='career_page_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('application_form',
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('career_page_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_page_id'], ['career_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_page_user',
    sa.Column('status', sa.Enum('active', 'blocked', name='career_page_user_status'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_page_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_page_id'], ['career_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('career_page_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_page_id'], ['career_page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_page_id', 'type', name='uix_career_page_type')
    )
    op.create_table('application_form_field',
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('application_form_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_form_id'], ['application_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_post',
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('status', sa.Enum('published', 'unpublished', name='job_post_status'), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_hide_salary', sa.Boolean(), nullable=False),
    sa.Column('payment_frequency', sa.Enum('hour', 'day', 'week', 'month', 'year', name='job_post_payment_frequency'), nullable=False),
    sa.Column('work_type', sa.Enum('full_time', 'part_time', 'temporary', 'freelance', 'internship', 'apprenticeship', 'contractor', 'consultancy', name='job_post_work_type'), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('minimum_salary', sa.Float(), nullable=False),
    sa.Column('maximum_salary', sa.Float(), nullable=False),
    sa.Column('header_key', sa.String(), nullable=True),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'THB', 'AUD', 'BRL', 'ETB', 'HKD', 'IDR', 'INR', 'MYR', 'PHP', 'PKR', 'SGD', 'CNY', 'ZAR', 'AFN', 'ALL', 'AED', 'ARS', 'AMD', 'AZN', 'BIF', 'XOF', 'BDT', 'BGN', 'BHD', 'BAM', 'BZD', 'BOB', 'BND', 'NOK', 'BWP', 'XAF', 'CAD', 'CHF', 'CLP', 'CDF', 'NZD', 'COP', 'KMF', 'CVE', 'CRC', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'MAD', 'GBP', 'GEL', 'GHS', 'GNF', 'GTQ', 'HNL', 'HRK', 'HUF', 'IRR', 'IQD', 'ISK', 'ILS', 'JMD', 'JOD', 'JPY', 'KZT', 'KES', 'KHR', 'KRW', 'KWD', 'LBP', 'LYD', 'LKR', 'MOP', 'MDL', 'MGA', 'MXN', 'MKD', 'MMK', 'MZN', 'MUR', 'NAD', 'NGN', 'NIO', 'NPR', 'OMR', 'PAB', 'PEN', 'PLN', 'PYG', 'QAR', 'RON', 'RUB', 'RWF', 'SAR', 'SDG', 'SOS', 'RSD', 'SEK', 'SYP', 'TOP', 'TTD', 'TND', 'TRY', 'TWD', 'TZS', 'UGX', 'UAH', 'UYU', 'UZS', 'VEF', 'VND', 'YER', 'MNT', 'SRD', 'ZWL', 'ZMW', 'AOA', 'HTG', 'BBD', 'PGK', name='job_post_currency'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('contract_details', sa.String(), nullable=False),
    sa.Column('external_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('application_form_id', sa.UUID(), nullable=False),
    sa.Column('career_page_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_form_id'], ['application_form.id'], ),
    sa.ForeignKeyConstraint(['career_page_id'], ['career_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('form', sa.JSON(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_post_translation',
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_post_translation')
    op.drop_table('application')
    op.drop_table('job_post')
    op.drop_table('application_form_field')
    op.drop_table('social_media')
    op.drop_table('career_page_user')
    op.drop_table('application_form')
    op.drop_table('user')
    op.drop_table('career_page')
    op.drop_table('applicant')
    # ### end Alembic commands ###
