"""Changed user id

Revision ID: 9cf369f0c3d8
Revises: 14d46861554b
Create Date: 2025-04-08 12:39:31.850194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf369f0c3d8'
down_revision: Union[str, None] = '14d46861554b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicant', 'full_name',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('applicant', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('applicant', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('applicant', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applicant', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('applicant', 'full_name',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###
