"""Updated logo5

Revision ID: 6ddf081fe4e5
Revises: b62f731e80ea
Create Date: 2025-04-03 13:33:21.855881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ddf081fe4e5'
down_revision: Union[str, None] = 'b62f731e80ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_job_post',
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('job_post_link',
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('external_job_post_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['external_job_post_id'], ['external_job_post.id'], ),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_post.id'], ),
    sa.PrimaryKeyConstraint('job_post_id', 'external_job_post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_post_link')
    op.drop_table('external_job_post')
    # ### end Alembic commands ###
