"""Location2

Revision ID: de8d88be7f57
Revises: ddaf0463f371
Create Date: 2025-04-09 11:49:26.420222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8d88be7f57'
down_revision: Union[str, None] = 'ddaf0463f371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'location', ['job_post_id'])
    op.drop_constraint('location_job_post_id_fkey', 'location', type_='foreignkey')
    op.create_foreign_key(None, 'location', 'job_post', ['job_post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.create_foreign_key('location_job_post_id_fkey', 'location', 'job_post', ['job_post_id'], ['id'])
    op.drop_constraint(None, 'location', type_='unique')
    # ### end Alembic commands ###
