"""Changed user id

Revision ID: 4201e55d4976
Revises: ed3086c86a21
Create Date: 2025-04-08 12:21:50.524075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4201e55d4976'
down_revision: Union[str, None] = 'ed3086c86a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_job_post', sa.Column('name', sa.String(length=600), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_job_post', 'name')
    # ### end Alembic commands ###
