"""Changed slug field

Revision ID: 2c3eef8cadc1
Revises: 6ddf081fe4e5
Create Date: 2025-04-03 13:36:56.063248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c3eef8cadc1'
down_revision: Union[str, None] = '6ddf081fe4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_form_field', 'slug',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_form_field', 'slug',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
