"""Fix tables

Revision ID: 0d9f2d4d3fa4
Revises: b6d6d11a17ae
Create Date: 2025-04-02 12:45:03.833993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9f2d4d3fa4'
down_revision: Union[str, None] = 'b6d6d11a17ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_page', sa.Column('language_code', sa.String(), nullable=False))
    op.drop_column('career_page', 'langue_code')
    op.add_column('job_post', sa.Column('minimum_salary', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('job_post', sa.Column('maximum_salary', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('job_post', 'minimun_salary')
    op.drop_column('job_post', 'maximun_salary')
    op.add_column('job_post_translation', sa.Column('language_code', sa.String(), nullable=False))
    op.drop_column('job_post_translation', 'langue_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post_translation', sa.Column('langue_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('job_post_translation', 'language_code')
    op.add_column('job_post', sa.Column('maximun_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('job_post', sa.Column('minimun_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('job_post', 'maximum_salary')
    op.drop_column('job_post', 'minimum_salary')
    op.add_column('career_page', sa.Column('langue_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('career_page', 'language_code')
    # ### end Alembic commands ###
