"""Location2

Revision ID: 944b0b5eabff
Revises: de8d88be7f57
Create Date: 2025-04-09 12:01:09.166240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944b0b5eabff'
down_revision: Union[str, None] = 'de8d88be7f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_post', 'name')
    op.drop_column('job_post', 'description')
    op.add_column('job_post_translation', sa.Column('name', sa.String(length=600), nullable=False))
    op.add_column('job_post_translation', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_post_translation', 'description')
    op.drop_column('job_post_translation', 'name')
    op.add_column('job_post', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_post', sa.Column('name', sa.VARCHAR(length=600), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
