"""Location3

Revision ID: 3d8380ba4173
Revises: 944b0b5eabff
Create Date: 2025-04-09 12:17:36.973636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8380ba4173'
down_revision: Union[str, None] = '944b0b5eabff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_language_code_job_post', 'job_post_translation', ['language_code', 'job_post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_language_code_job_post', 'job_post_translation', type_='unique')
    # ### end Alembic commands ###
