"""Created CareerPageUser

Revision ID: a66af220a637
Revises: 
Create Date: 2025-04-01 19:48:56.617053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66af220a637'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_page',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('favicon_url', sa.String(), nullable=True),
    sa.Column('social_media_url', sa.String(), nullable=True),
    sa.Column('langue_code', sa.String(), nullable=False),
    sa.Column('is_referral_program', sa.Boolean(), nullable=False),
    sa.Column('is_display_organization', sa.Boolean(), nullable=False),
    sa.Column('is_powered_by_manatal', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('contact_website', sa.String(), nullable=False),
    sa.Column('is_share_job_social_media', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_page_user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_page_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_page_id'], ['career_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'career_page_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_page_user')
    op.drop_table('user')
    op.drop_table('career_page')
    # ### end Alembic commands ###
