"""Add status to the status6

Revision ID: a45d1cf6e28b
Revises: aa1911ab2865
Create Date: 2025-04-07 20:01:02.034437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45d1cf6e28b'
down_revision: Union[str, None] = 'aa1911ab2865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
job_post_currency = sa.Enum('EUR', 'USD', 'THB', 'AUD', 'BRL', 'ETB', 'HKD', 'IDR', 'INR', 'MYR', 'PHP', 'PKR', 'SGD', 'CNY', 'ZAR', 'AFN', 'ALL', 'AED', 'ARS', 'AMD', 'AZN', 'BIF', 'XOF', 'BDT', 'BGN', 'BHD', 'BAM', 'BZD', 'BOB', 'BND', 'NOK', 'BWP', 'XAF', 'CAD', 'CHF', 'CLP', 'CDF', 'NZD', 'COP', 'KMF', 'CVE', 'CRC', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'MAD', 'GBP', 'GEL', 'GHS', 'GNF', 'GTQ', 'HNL', 'HRK', 'HUF', 'IRR', 'IQD', 'ISK', 'ILS', 'JMD', 'JOD', 'JPY', 'KZT', 'KES', 'KHR', 'KRW', 'KWD', 'LBP', 'LYD', 'LKR', 'MOP', 'MDL', 'MGA', 'MXN', 'MKD', 'MMK', 'MZN', 'MUR', 'NAD', 'NGN', 'NIO', 'NPR', 'OMR', 'PAB', 'PEN', 'PLN', 'PYG', 'QAR', 'RON', 'RUB', 'RWF', 'SAR', 'SDG', 'SOS', 'RSD', 'SEK', 'SYP', 'TOP', 'TTD', 'TND', 'TRY', 'TWD', 'TZS', 'UGX', 'UAH', 'UYU', 'UZS', 'VEF', 'VND', 'YER', 'MNT', 'SRD', 'ZWL', 'ZMW', 'AOA', 'HTG', 'BBD', 'PGK', name='job_post_currency')


def upgrade() -> None:
    """Upgrade schema."""
    job_post_currency.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post', sa.Column('currency', job_post_currency, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_post', 'currency')
    # ### end Alembic commands ###
