"""Add status to the uix_career_page_type

Revision ID: 7a02e0046427
Revises: 01f56eea5654
Create Date: 2025-04-07 15:02:53.362832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a02e0046427'
down_revision: Union[str, None] = '01f56eea5654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_career_page_type', 'social_media', ['career_page_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_career_page_type', 'social_media', type_='unique')
    # ### end Alembic commands ###
