"""Add status to the CareerPageUser3

Revision ID: 01f56eea5654
Revises: 2f57c4e85d72
Create Date: 2025-04-04 16:35:02.651772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f56eea5654'
down_revision: Union[str, None] = '2f57c4e85d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post', sa.Column('header_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_post', 'header_key')
    # ### end Alembic commands ###
