"""Updated logo

Revision ID: d02c5fa76867
Revises: a4f93e231c69
Create Date: 2025-04-03 09:27:11.900504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import FileType
from src.aws.client import PublicAssetS3Storage

# revision identifiers, used by Alembic.
revision: str = 'd02c5fa76867'
down_revision: Union[str, None] = 'a4f93e231c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_page', sa.Column('logo', FileType(PublicAssetS3Storage()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_page', 'logo')
    # ### end Alembic commands ###
