"""Add status to the status

Revision ID: 84ae0716f2f5
Revises: 46ecc7c2ba0f
Create Date: 2025-04-07 19:04:17.586350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ae0716f2f5'
down_revision: Union[str, None] = '46ecc7c2ba0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
job_post_status_enum = sa.Enum('published', 'unpublished', name='job_post_status')

def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create ENUM type
    job_post_status_enum.create(op.get_bind(), checkfirst=True)

    # 2. Use raw SQL to alter the column with explicit cast
    op.execute("""
        ALTER TABLE job_post
        ALTER COLUMN status TYPE job_post_status
        USING status::job_post_status
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_post', 'status',
               existing_type=sa.Enum('published', 'unpublished', name='job_post_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
