"""Add status to the status3

Revision ID: 9115307813b9
Revises: 84ae0716f2f5
Create Date: 2025-04-07 19:39:10.375229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9115307813b9'
down_revision: Union[str, None] = '84ae0716f2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
job_post_payment_frequency = sa.Enum('hour', 'day', 'week', 'month', 'year', name='job_post_payment_frequency')

def upgrade() -> None:
    """Upgrade schema."""
    job_post_payment_frequency.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_post', 'payment_frequency',
               existing_type=sa.VARCHAR(),
               type_=job_post_payment_frequency,
               existing_nullable=False, 
               postgresql_using="payment_frequency::job_post_payment_frequency",)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_post', 'payment_frequency',
               existing_type=sa.Enum('hour', 'day', 'week', 'month', 'year', name='job_post_payment_frequency'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
