"""Add status to the CareerPageUser

Revision ID: eced6b7430e6
Revises: 
Create Date: 2025-04-04 15:51:13.510507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eced6b7430e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant',
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('career_page',
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('job_post_limit', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('favicon_url', sa.String(), nullable=True),
    sa.Column('social_media_url', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('is_referral_program', sa.Boolean(), nullable=False),
    sa.Column('is_display_organization', sa.Boolean(), nullable=False),
    sa.Column('is_powered_by_manatal', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('contact_website', sa.String(), nullable=False),
    sa.Column('is_share_job_social_media', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_job_post',
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('user',
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('application_form',
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('career_page_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_page_id'], ['career_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_page_user',
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', name='usercareerpagestatus'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_page_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_page_id'], ['career_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('career_page_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_page_id'], ['career_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_form_field',
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('application_form_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_form_id'], ['application_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_post',
    sa.Column('name', sa.String(length=600), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_hide_salary', sa.Boolean(), nullable=False),
    sa.Column('payment_frequency', sa.String(), nullable=False),
    sa.Column('work_type', sa.String(), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('minimum_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('maximum_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('application_form_id', sa.UUID(), nullable=False),
    sa.Column('career_page_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_form_id'], ['application_form.id'], ),
    sa.ForeignKeyConstraint(['career_page_id'], ['career_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('form', sa.JSON(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_post_link',
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('external_job_post_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['external_job_post_id'], ['external_job_post.id'], ),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_post.id'], ),
    sa.PrimaryKeyConstraint('job_post_id', 'external_job_post_id')
    )
    op.create_table('job_post_translation',
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('job_post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_post_translation')
    op.drop_table('job_post_link')
    op.drop_table('application')
    op.drop_table('job_post')
    op.drop_table('application_form_field')
    op.drop_table('social_media')
    op.drop_table('career_page_user')
    op.drop_table('application_form')
    op.drop_table('user')
    op.drop_table('external_job_post')
    op.drop_table('career_page')
    op.drop_table('applicant')
    # ### end Alembic commands ###
