"""Changed user id

Revision ID: adcdff2f4caa
Revises: f3e5ac9b6fad
Create Date: 2025-04-08 20:16:43.624168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adcdff2f4caa'
down_revision: Union[str, None] = 'f3e5ac9b6fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('application_job_post_id_fkey', 'application', type_='foreignkey')
    op.drop_constraint('application_applicant_id_fkey', 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'job_post', ['job_post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'application', 'applicant', ['applicant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key('application_applicant_id_fkey', 'application', 'applicant', ['applicant_id'], ['id'])
    op.create_foreign_key('application_job_post_id_fkey', 'application', 'job_post', ['job_post_id'], ['id'])
    # ### end Alembic commands ###
