from enum import StrEnum


class UserCareerPageStatus(StrEnum):
    """
    Enum for user career page status.
    """

    active = "active"
    blocked = "blocked"


class Currency(StrEnum):
    """
    Enum for currency.
    """

    EUR = "Euro"
    USD = "US Dollar"
    THB = "Thai Baht"
    AUD = "Australian Dollar"
    BRL = "Brazilian Real"
    ETB = "Ethiopian Birr"
    HKD = "Hong Kong Dollar"
    IDR = "Indonesian Rupiah"
    INR = "Indian Rupee"
    MYR = "Malaysian Ringgit"
    PHP = "Philippine Peso"
    PKR = "Pakistani Rupee"
    SGD = "Singapore Dollar"
    CNY = "Chinese Yuan"
    ZAR = "South African Rand"
    AFN = "Afghan Afghani"
    ALL = "Albanian Lek"
    AED = "United Arab Emirates Dirham"
    ARS = "Argentine Peso"
    AMD = "Armenian Dram"
    AZN = "Azerbaijani Manat"
    BIF = "Burundian Franc"
    XOF = "CFA Franc BCEAO"
    BDT = "Bangladeshi Taka"
    BGN = "Bulgarian Lev"
    BHD = "Bahraini Dinar"
    BAM = "Bosnia-Herzegovina Convertible Mark"
    BZD = "Belize Dollar"
    BOB = "Bolivian Boliviano"
    BND = "Brunei Dollar"
    NOK = "Norwegian Krone"
    BWP = "Botswanan Pula"
    XAF = "CFA Franc BEAC"
    CAD = "Canadian Dollar"
    CHF = "Swiss Franc"
    CLP = "Chilean Peso"
    CDF = "Congolese Franc"
    NZD = "New Zealand Dollar"
    COP = "Colombian Peso"
    KMF = "Comorian Franc"
    CVE = "Cape Verdean Escudo"
    CRC = "Costa Rican Colón"
    CZK = "Czech Republic Koruna"
    DJF = "Djiboutian Franc"
    DKK = "Danish Krone"
    DOP = "Dominican Peso"
    DZD = "Algerian Dinar"
    EGP = "Egyptian Pound"
    ERN = "Eritrean Nakfa"
    MAD = "Moroccan Dirham"
    GBP = "British Pound Sterling"
    GEL = "Georgian Lari"
    GHS = "Ghanaian Cedi"
    GNF = "Guinean Franc"
    GTQ = "Guatemalan Quetzal"
    HNL = "Honduran Lempira"
    HRK = "Croatian Kuna"
    HUF = "Hungarian Forint"
    IRR = "Iranian Rial"
    IQD = "Iraqi Dinar"
    ISK = "Icelandic Króna"
    ILS = "Israeli New Sheqel"
    JMD = "Jamaican Dollar"
    JOD = "Jordanian Dinar"
    JPY = "Japanese Yen"
    KZT = "Kazakhstani Tenge"
    KES = "Kenyan Shilling"
    KHR = "Cambodian Riel"
    KRW = "South Korean Won"
    KWD = "Kuwaiti Dinar"
    LBP = "Lebanese Pound"
    LYD = "Libyan Dinar"
    LKR = "Sri Lankan Rupee"
    MOP = "Macanese Pataca"
    MDL = "Moldovan Leu"
    MGA = "Malagasy Ariary"
    MXN = "Mexican Peso"
    MKD = "Macedonian Denar"
    MMK = "Myanma Kyat"
    MZN = "Mozambican Metical"
    MUR = "Mauritian Rupee"
    NAD = "Namibian Dollar"
    NGN = "Nigerian Naira"
    NIO = "Nicaraguan Córdoba"
    NPR = "Nepalese Rupee"
    OMR = "Omani Rial"
    PAB = "Panamanian Balboa"
    PEN = "Peruvian Nuevo Sol"
    PLN = "Polish Zloty"
    PYG = "Paraguayan Guarani"
    QAR = "Qatari Rial"
    RON = "Romanian Leu"
    RUB = "Russian Ruble"
    RWF = "Rwandan Franc"
    SAR = "Saudi Riyal"
    SDG = "Sudanese Pound"
    SOS = "Somali Shilling"
    RSD = "Serbian Dinar"
    SEK = "Swedish Krona"
    SYP = "Syrian Pound"
    TOP = "Tongan Pa'anga"
    TTD = "Trinidad and Tobago Dollar"
    TND = "Tunisian Dinar"
    TRY = "Turkish Lira"
    TWD = "New Taiwan Dollar"
    TZS = "Tanzanian Shilling"
    UGX = "Ugandan Shilling"
    UAH = "Ukrainian Hryvnia"
    UYU = "Uruguayan Peso"
    UZS = "Uzbekistan Som"
    VEF = "Venezuelan Bolívar"
    VND = "Vietnamese Dong"
    YER = "Yemeni Rial"
    MNT = "Mongolian Tögrög"
    SRD = "Suriname Dollar"
    ZWL = "Zimbabwe Dollar"
    ZMW = "Zambian Kwacha"
    AOA = "Angolan Kwanza"
    HTG = "Haitian Gourde"
    BBD = "Barbados Dollar"
    PGK = "Papua New Guinean Kina"


class JobPostStatus(StrEnum):
    """
    Enum for job post status.
    """

    published = "published"
    unpublished = "unpublished"
